---
classes:
  - role::monitoring

graphite::gr_pip_install: true
graphite::secret_key: 'mai0raepo2loofeese5Ooph2uo0zee7i'
graphite::gr_timezone: 'Europe/Warsaw'
graphite::gr_storage_schemas:
  - name: 'carbon'
    pattern: '^carbon\.'
    retentions: '1m:90d'
  - name: 'default'
    pattern: ".*"
    retentions: "1s:2d,1m:7d,5m:2y"

collectd::read_threads: 5 #default 5
collectd::purge: true
collectd::recurse: true
collectd::purge_config: true
collectd::minimum_version: '5.4'

xstream::carbon:
  'collectd::plugin::write_graphite::carbon':
    'lxc':
      graphitehost: 'localhost'
      graphiteport: 2003
      graphiteprefix: ''
      protocol: 'tcp'
      interval: 1

collectd::plugin::curl_json:
  'php':
    url: 'http://127.0.0.1/php-status?json'
    user: healthcheck
    password: healthcheck
    instance: 'app_php'
    interval: 10
    keys:
      'processes/pid':
        type: 'gauge'
      # 'message_stats/confirm':
      #   type: 'counter'
      # 'message_stats/return_unroutable':
      #   type: 'counter'
      # 'message_stats/disk_reads':
      #   type: 'counter'
      # 'message_stats/disk_writes':
      #   type: 'counter'
      # 'message_stats/get':
      #   type: 'counter'
      # 'message_stats/get_no_ack':
      #   type: 'counter'
      # 'message_stats/deliver':
      #   type: 'counter'
      # 'message_stats/redeliver':
      #   type: 'counter'
      # 'message_stats/ack':
      #   type: 'counter'
      # 'message_stats/deliver_get':
      #   type: 'counter'

      # 'queue_totals/messages_ready':
      #   type: 'counter'
      # 'queue_totals/messages_unacknowledged':
      #   type: 'counter'
      # 'queue_totals/messages':
      #   type: 'counter'

      # 'object_totals/consumers':
      #   type: 'gauge'
      # 'object_totals/queues':
      #   type: 'gauge'
      # 'object_totals/exchanges':
      #   type: 'gauge'
      # 'object_totals/connections':
      #   type: 'gauge'
      # 'object_totals/channels':
      #   type: 'gauge'


# single host only
collectd::plugin::nginx::url: 'http://127.0.0.1:80/server-status'
# collectd::plugin::nginx::user: 'xstream'
# collectd::plugin::nginx::password: 'nginx_status'

firewall:
  '100 allow all ports from local networks':
    source: '10.0.0.0/8'
    action: 'accept'